export interface ROUTES_TYPES {
  ANIME_LIST_SCREEN: 'ANIME_LIST_SCREEN';
  FAVORITE_ANIME_SCREEN: 'FAVORITE_ANIME_SCREEN';
}

const ROUTES: ROUTES_TYPES = {
  ANIME_LIST_SCREEN: 'ANIME_LIST_SCREEN',
  FAVORITE_ANIME_SCREEN: 'FAVORITE_ANIME_SCREEN',
};

export default ROUTES;
