export interface ROUTES_TYPES {
  ANIME_LIST_SCREEN: 'ANIME_LIST_SCREEN';
  FACT_ANIME: 'FACT_ANIME';
}

const ROUTES: ROUTES_TYPES = {
  ANIME_LIST_SCREEN: 'ANIME_LIST_SCREEN',
  FACT_ANIME: 'FACT_ANIME',
};

export default ROUTES;
